### ISSUE TITLE
Failed tests and other side-effect errors related to global shortcut keys

### ISSUE THREAD

**Issue by bingenito** [Morgan-Stanley/desktopJS#218]
PR #214 introduced some failed tests that were not caught because of #217 

Global shortcuts require minimum OpenFin runtime of 9.61.32.34
    Unavailable in OpenFin is unavailable on container: failed

ElectronGlobalShortcutManager
  invokes underlying Electron
{ Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at new ElectronContainer (/home/travis/build/Morgan-Stanley/desktopJS/packages/desktopjs-electron/build/src/electron.js:9:31216)
    at UserContext.<anonymous> (/home/travis/build/Morgan-Stanley/desktopJS/packages/desktopjs-electron/build/tests/electron.spec.js:969:29)
    at QueueRunner.attempt (/home/travis/build/Morgan-Stanley/desktopJS/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4816:44)
    at QueueRunner.run (/home/travis/build/Morgan-Stanley/desktopJS/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4854:25)
    at runNext (/home/travis/build/Morgan-Stanley/desktopJS/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4784:18)
    at next (/home/travis/build/Morgan-Stanley/desktopJS/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4791:11) code: 'MODULE_NOT_FOUND' }
